[build]
  publish = "site"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# If you prefer not to use `_redirects`, you can uncomment the redirect below.
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200
